@startuml
abstract class Asset{}
abstract class TangibleAsset{}
abstract class IntangibleAsset{}
interface Thing{}
Asset<|--TangibleAsset
Asset<|--IntangibleAsset
Thing<|--TangibleAsset
TangibleAsset<|--Book
TangibleAsset<|--Computer
IntangibleAsset<|--Program
@enduml