@startuml
scale 2

Hero : int hp
Hero : void attack()

Cleric : int hp
Cleric : int mp

Slime <|-- PoisonSlime
Slime : String suffix
Slime : int hp
Slime : void attack(Hero hero)

PoisonSlime : - int poisonCount
PoisonSlime : PoisonSlime(String suffix)
PoisonSlime : void attack(Hero hero)

Wizard : int hp
Wizard : int mp
Wizard : void heal(Hero hero)

Wizard <|-- GreatWizard
GreatWizard : void heal(Hero hero)



'SuperHero : bool isFlying
'SuperHero : void fly()
'SuperHero : void land()
'
'Character <|-- Hero
'Character <|-- Cleric
'Character <|-- Wizard
'Wizard : int mp
'Wizard : void heal(Hero hero)
'
'Wizard <|-- GreatWizard

@enduml