@startuml
'https://plantuml.com/class-diagram
class Cleric {
    - name : String
    - hp : int
    - maxHp : int

    + Cleric(name : String)
    + selfAid() : void
    + pray(sec : int) : int
}

@enduml