@startuml
'https://plantuml.com/class-diagram

    class Cleric {
        String name
        int hp
        int mp
        void selfAid()

    }
    class Hero {
        String name
        int hp

        void run()

    }

@enduml