@startuml
'https://plantuml.com/class-diagram

class TangibleAsset {
String name
int price
- String color
}

class computer {
String name
int price
String color
- String makername

}

class Book {
String name
int price
String color
-String isbn
}

class Asset {
- String name
- int price
}

class IntangibleAsset {
String name
int price
}

class Patent {
String name
int price
}

IntangibleAsset <|.. Patent
Asset <|..IntangibleAsset
Asset <|..TangibleAsset
TangibleAsset <|..Book
TangibleAsset <|.. computer

@enduml