@startuml

abstract class Asset {}

abstract class TangibleAsset extends Asset {
String name
int price
String color
}

class Book extends TangibleAsset {
String isbn
}

class Computer extends TangibleAsset {
String makerName
}

abstract class IntangibleAsset extends Asset {
}

class Patent extends IntangibleAsset {
}

interface Thing {
double weight
}

@enduml