@startuml

class Cleric {
    static final int MAX_HP
    static final int MAX_MP
    static final int SELF_AID_MP_COST
    static final int PRAY_RECOVERY_RANDOM_BOUND

    String name
    int hp
    int mp

    void selfAid()
    int pray(int sec)
}

class Hero {
    static int money

    String name
    int hp
    int mp

    static void setRandomMoney()
    void attack()
    void counterattacked()
    void run()
    void sit(int sec)
    void slip()
    void sleep()
    void bye()
    - void die()
}

class Wand {
    static final double MIN_POWER
    static final double MAX_POWER
    static final int MIN_NAME_LENGTH

    double power
    String name
}

class Wizard {
    static final int MIN_HP
    static final int MAX_HP
    static final int MIN_MP
    static final int MAX_MP
    static final int BASE_HEAL_POINT
    static final int MIN_NAME_LENGTH

    int hp
    int mp
    String name
    Wand wand

    - int ensureAtLeast(int value, int min)
    - int preventNegativeValue(int value)
    void heal(Hero hero)
}

@enduml